In [93]:
import os
import numpy as np
import matplotlib.pyplot as plt

In [94]:
import tensorflow as tf
tf.__version__

'2.12.0'

In [95]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, GRU, LSTM, Dense

# 2. Keras로 LSTM 구현하기

https://keras.io/api/layers/recurrent_layers/lstm/

사실 실제로 SimpleRNN이 사용되는 경우는 거의 없습니다. 이보다는 LSTM이나 GRU을 주로 사용하는데, 이번에는 임의의 입력에 대해서 LSTM을 사용할 경우를 보겠습니다.

In [97]:
John = [1,0,0,0]
loves = [0,1,0,0]
Jane = [0,0,1,0]
Alex = [0,0,0,1]

train_X = np.array([
    [ John, loves, Jane ],
    [ Jane, loves, Alex ]
]).astype(np.float32)

S = [0] # subject
V = [1] # verb
O = [2] # object

idx2tag = ['S', 'V', 'O']

train_Y = np.array([[S, V, O], [S, V, O]]).astype(np.float32)

print("train_y", train_Y)
print("train_X의 shape", train_X.shape)
print("train_Y의 shape", train_Y.shape)

train_y [[[0.]
  [1.]
  [2.]]

 [[0.]
  [1.]
  [2.]]]
train_X의 shape (2, 3, 4)
train_Y의 shape (2, 3, 1)


In [99]:
train_X.shape

(2, 3, 4)

In [100]:
lstm = LSTM(10, return_sequences = True, return_state = True)
output = lstm(train_X) # 전체 t의 ht,  # 마지막 시점 ht, # 마지막 시점의 Ct

In [101]:
len(output)

3

In [ ]:
output[0] # 전체 t의 ht

<tf.Tensor: shape=(2, 3, 10), dtype=float32, numpy=
array([[[ 5.95213249e-02,  2.73347925e-02,  5.00698201e-02,
          4.23972011e-02, -1.25190709e-02,  1.75359100e-02,
          5.66500537e-02,  2.91814208e-02, -8.17760080e-03,
         -2.60345009e-03],
        [ 1.06368870e-01,  1.00587800e-01,  4.65391465e-02,
         -3.44404206e-02, -8.89488147e-05, -2.57313643e-02,
          8.66490528e-02,  5.96799031e-02,  1.79297868e-02,
          6.03204705e-02],
        [ 3.68608497e-02,  1.15720205e-01,  7.18055815e-02,
         -2.49844361e-02,  1.29834032e-02,  1.69115402e-02,
         -3.74900270e-03,  2.42530648e-02, -1.59018021e-03,
         -1.13685466e-02]],

       [[-2.82654651e-02,  5.89429215e-02,  3.58384848e-02,
          3.85188195e-03,  2.03021243e-02,  3.63659523e-02,
         -7.62370005e-02, -1.89976431e-02, -2.16783658e-02,
         -4.40223143e-02],
        [ 5.20731546e-02,  1.27881497e-01,  3.09631098e-02,
         -6.30963743e-02,  2.34837849e-02, -1.68329757e-02

In [ ]:
output[0][:, -1] # 전체 t의 ht 에서 마지막 시점만 따로 출력

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[ 0.03686085,  0.11572021,  0.07180558, -0.02498444,  0.0129834 ,
         0.01691154, -0.003749  ,  0.02425306, -0.00159018, -0.01136855],
       [-0.054012  ,  0.11697462, -0.02747288, -0.15865211, -0.05454956,
        -0.01471838, -0.06649601,  0.04988749, -0.02302955, -0.01298162]],
      dtype=float32)>

In [ ]:
output[1] # 마지막 시점 ht

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[ 0.03686085,  0.11572021,  0.07180558, -0.02498444,  0.0129834 ,
         0.01691154, -0.003749  ,  0.02425306, -0.00159018, -0.01136855],
       [-0.054012  ,  0.11697462, -0.02747288, -0.15865211, -0.05454956,
        -0.01471838, -0.06649601,  0.04988749, -0.02302955, -0.01298162]],
      dtype=float32)>

In [ ]:
output[2] # 마지막 시점의 Ct

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[ 0.08789746,  0.22357422,  0.1552583 , -0.05953043,  0.0281082 ,
         0.02987351, -0.00785817,  0.0534323 , -0.00337005, -0.0197007 ],
       [-0.11076517,  0.21367313, -0.06207175, -0.2991258 , -0.11800462,
        -0.03353077, -0.11817683,  0.08700105, -0.05708504, -0.02405307]],
      dtype=float32)>

In [ ]:
# return_sequences = True

lstm = LSTM(3, return_sequences=True, return_state=True)
whole_seq_output, final_hidden_state, final_cell_state = lstm(train_X)

print('whole_seq_output: {}, shape: {}'.format(whole_seq_output, whole_seq_output.shape))
print('final_hidden_state : {}, shape: {}'.format(final_hidden_state, final_hidden_state.shape))
print('final_cell_state : {}, shape: {}'.format(final_cell_state, final_cell_state.shape))

whole_seq_output: [[[ 0.08575397 -0.02023415  0.0967318 ]
  [-0.0143228  -0.14939667 -0.06404299]
  [-0.03122702  0.07728968 -0.05782751]]

 [[-0.03024196  0.17542334 -0.02640349]
  [-0.09294365 -0.04716035 -0.14726636]
  [-0.04423431 -0.10094055 -0.09628483]]], shape: (2, 3, 3)
final_hidden_state : [[-0.03122702  0.07728968 -0.05782751]
 [-0.04423431 -0.10094055 -0.09628483]], shape: (2, 3)
final_cell_state : [[-0.06366488  0.13244489 -0.11224427]
 [-0.11746147 -0.19040419 -0.16830625]], shape: (2, 3)


In [ ]:
from tensorflow.keras import layers, models

model = models.Sequential() #모델 호출
model.add(
    layers.LSTM(units=5,
                input_shape = (3, 4),
                return_sequences = True,
                name='LSTM-1'))

model.add(
    layers.Dense(
        units=3,
        activation='softmax',
        name='hidden-to-output')) # 출력을 위한 FFN


model.compile(
    loss='sparse_categorical_crossentropy',
    optimizer= 'adam',
    metrics=['accuracy'])


In [ ]:
model.fit(train_X, train_Y, epochs= 100)

Epoch 1/100
1/1 [==============================] - 2s 2s/step - loss: 1.0970 - accuracy: 0.3333
Epoch 2/100
1/1 [==============================] - 0s 14ms/step - loss: 1.0960 - accuracy: 0.3333
Epoch 3/100
1/1 [==============================] - 0s 12ms/step - loss: 1.0950 - accuracy: 0.3333
Epoch 4/100
1/1 [==============================] - 0s 13ms/step - loss: 1.0940 - accuracy: 0.3333
Epoch 5/100
1/1 [==============================] - 0s 14ms/step - loss: 1.0931 - accuracy: 0.3333
Epoch 6/100
1/1 [==============================] - 0s 15ms/step - loss: 1.0921 - accuracy: 0.3333
Epoch 7/100
1/1 [==============================] - 0s 12ms/step - loss: 1.0912 - accuracy: 0.3333
Epoch 8/100
1/1 [==============================] - 0s 12ms/step - loss: 1.0902 - accuracy: 0.3333
Epoch 9/100
1/1 [==============================] - 0s 11ms/step - loss: 1.0893 - accuracy: 0.3333
Epoch 10/100
1/1 [==============================] - 0s 12ms/step - loss: 1.0884 - accuracy: 0.3333
Epoch 11/100
1/1 [===

In [ ]:
predictions = model.predict(train_X)
for i, prediction in enumerate(predictions):
  print(prediction)
  print(np.argmax(prediction, axis=1))
  result_str = [idx2tag[c] for c in np.argmax(prediction, axis=1) ]
  print("\tPrediction str: ", "".join(result_str))


1/1 [==============================] - 1s 717ms/step
[[0.3393817  0.36409453 0.29652378]
 [0.2919191  0.39315116 0.31492972]
 [0.296538   0.32258716 0.3808749 ]]
[1 1 2]
	Prediction str:  VVO
[[0.3585297  0.29287627 0.34859407]
 [0.3165617  0.33784285 0.34559545]
 [0.30826566 0.28944558 0.40228876]]
[0 2 2]
	Prediction str:  SOO


In [ ]:
model.summary()

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 LSTM-1 (LSTM)               (None, 3, 5)              200       
                                                                 
 hidden-to-output (Dense)    (None, 3, 3)              18        
                                                                 
Total params: 218
Trainable params: 218
Non-trainable params: 0
_________________________________________________________________


In [ ]:
for model_weight in model.weights:
    print(model_weight.name, '=>', model_weight.shape)

LSTM-1/lstm_cell_14/kernel:0 => (4, 20)
LSTM-1/lstm_cell_14/recurrent_kernel:0 => (5, 20)
LSTM-1/lstm_cell_14/bias:0 => (20,)
hidden-to-output/kernel:0 => (5, 3)
hidden-to-output/bias:0 => (3,)


### 문제1

In [ ]:
model = Sequential()
model.add(LSTM(7, input_shape=(100,5)))
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_2 (LSTM)               (None, 7)                 364       
                                                                 
Total params: 364
Trainable params: 364
Non-trainable params: 0
_________________________________________________________________


- W_forget : (num_units + input_dim + 1) * num_units
- W_input : (num_units + input_dim + 1) * num_units
- W_output : (num_units + input_dim + 1) * num_units
- W_cell : (num_units + input_dim + 1) * num_units

### 문제2

In [ ]:
model = Sequential()
model.add(LSTM(5, input_shape = (2, 10)))
model.add(Dense(1))
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_3 (LSTM)               (None, 5)                 320       
                                                                 
 dense (Dense)               (None, 1)                 6         
                                                                 
Total params: 326
Trainable params: 326
Non-trainable params: 0
_________________________________________________________________


- W_forget : (num_units + input_dim + 1) * num_units
- W_input : (num_units + input_dim + 1) * num_units
- W_output : (num_units + input_dim + 1) * num_units
- W_cell : (num_units + input_dim + 1) * num_units

In [ ]:
# weight 개수 카운팅

### 문제3

In [ ]:
model = Sequential()
model.add(LSTM(5, input_shape = (2, 10), return_sequences=True))
model.add(LSTM(7))
model.add(Dense(1))
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_4 (LSTM)               (None, 2, 5)              320       
                                                                 
 lstm_5 (LSTM)               (None, 7)                 364       
                                                                 
 dense_1 (Dense)             (None, 1)                 8         
                                                                 
Total params: 692
Trainable params: 692
Non-trainable params: 0
_________________________________________________________________


# 3. Keras로 GRU 구현하기

https://keras.io/api/layers/recurrent_layers/gru/

In [ ]:
train_X

array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]],

       [[0., 0., 1., 0.],
        [0., 1., 0., 0.],
        [0., 0., 0., 1.]]], dtype=float32)

In [ ]:
gru = GRU(10, return_sequences = True, return_state = True)
whole_hidden_state, final_hidden_state = gru(train_X)

In [ ]:
whole_hidden_state.shape

TensorShape([2, 3, 10])

In [ ]:
final_hidden_state.shape

TensorShape([2, 10])

In [ ]:
# return_sequences = True
gru = GRU(3, return_sequences=True, return_state=True)
whole_sequence_output, final_state= gru(train_X)

print('whole_seq_output: {}, shape: {}'.format(whole_seq_output, whole_seq_output.shape))
print('final_state : {}, shape: {}'.format(final_state, final_state.shape))

whole_seq_output: [[[-0.09133016 -0.02071412  0.14170164]
  [ 0.02361282  0.06159054  0.03471249]
  [ 0.06012786 -0.04471743 -0.08892121]]

 [[ 0.03587217 -0.0941782  -0.11587585]
  [ 0.08149255  0.02020295 -0.18497597]
  [ 0.03355836 -0.02213107 -0.14921774]]], shape: (2, 3, 3)
final_state : [[ 0.10870809  0.3283546  -0.2419539 ]
 [-0.13706805 -0.10124536 -0.31973392]], shape: (2, 3)


In [102]:
from tensorflow.keras import layers, models

model = models.Sequential() #모델 호출
model.add(
    layers.GRU(
        units=5,
        input_shape =(3, 4),
        return_sequences = True,
        name='GRU-1')) # RNN 호출

# reset_after : keras 구현을 하면서 병렬처리를 위해 공식을 수정(bias를 2개로 나눔)하였는데, 원래 논문에 나온 공식으로 계산하기 위해 False로 수정

model.add(
    layers.Dense(
        units=3,
        activation='softmax',
        name='hidden-to-output')) # 출력을 위한 FFN


model.compile(
    loss='sparse_categorical_crossentropy',
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.01),
    metrics=['accuracy'])


In [103]:
model.fit(train_X, train_Y, epochs= 100)

Epoch 1/100
1/1 [==============================] - 3s 3s/step - loss: 1.0815 - accuracy: 0.3333
Epoch 2/100
1/1 [==============================] - 0s 13ms/step - loss: 1.0674 - accuracy: 0.3333
Epoch 3/100
1/1 [==============================] - 0s 12ms/step - loss: 1.0537 - accuracy: 0.5000
Epoch 4/100
1/1 [==============================] - 0s 16ms/step - loss: 1.0404 - accuracy: 0.5000
Epoch 5/100
1/1 [==============================] - 0s 14ms/step - loss: 1.0273 - accuracy: 0.5000
Epoch 6/100
1/1 [==============================] - 0s 14ms/step - loss: 1.0144 - accuracy: 0.5000
Epoch 7/100
1/1 [==============================] - 0s 12ms/step - loss: 1.0018 - accuracy: 0.6667
Epoch 8/100
1/1 [==============================] - 0s 13ms/step - loss: 0.9893 - accuracy: 0.6667
Epoch 9/100
1/1 [==============================] - 0s 12ms/step - loss: 0.9770 - accuracy: 0.6667
Epoch 10/100
1/1 [==============================] - 0s 11ms/step - loss: 0.9648 - accuracy: 0.6667
Epoch 11/100
1/1 [===

In [104]:
predictions = model.predict(train_X)
for i, prediction in enumerate(predictions):
  print(prediction)
  print(np.argmax(prediction, axis=1))
  result_str = [idx2tag[c] for c in np.argmax(prediction, axis=1) ]
  print("\tPrediction str: ", "".join(result_str))


1/1 [==============================] - 0s 411ms/step
[[0.98696834 0.01087731 0.00215445]
 [0.01300731 0.9851386  0.00185408]
 [0.0110564  0.00125612 0.9876875 ]]
[0 1 2]
	Prediction str:  SVO
[[0.9762813  0.01630823 0.00741052]
 [0.01375031 0.9840776  0.00217211]
 [0.0065681  0.00119541 0.99223644]]
[0 1 2]
	Prediction str:  SVO


In [105]:
model.summary()

Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 GRU-1 (GRU)                 (None, 3, 5)              165       
                                                                 
 hidden-to-output (Dense)    (None, 3, 3)              18        
                                                                 
Total params: 183
Trainable params: 183
Non-trainable params: 0
_________________________________________________________________


In [106]:
for model_weight in model.weights:
    print(model_weight.name, '=>', model_weight.shape)

GRU-1/gru_cell/kernel:0 => (4, 15)
GRU-1/gru_cell/recurrent_kernel:0 => (5, 15)
GRU-1/gru_cell/bias:0 => (2, 15)
hidden-to-output/kernel:0 => (5, 3)
hidden-to-output/bias:0 => (3,)


### 문제1

In [109]:
model = Sequential()
model.add(GRU(9, input_dim = 10, return_sequences=True))
# reset_after : keras 구현을 하면서 병렬처리를 위해 공식을 수정(bias를 2개로 나눔)하였는데, 원래 논문에 나온 공식으로 계산하기 위해 False로 수정
model.add(GRU(6))
model.add(Dense(3))
model.summary()

Model: "sequential_12"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 gru_4 (GRU)                 (None, None, 9)           567       
                                                                 
 gru_5 (GRU)                 (None, 6)                 306       
                                                                 
 dense_4 (Dense)             (None, 3)                 21        
                                                                 
Total params: 894
Trainable params: 894
Non-trainable params: 0
_________________________________________________________________


- W_reset : (num_units + input_dim + 1) * num_units
- W_update : (num_units + input_dim + 1) * num_units
- W_new : (num_units + input_dim + 1) * num_units


In [ ]:
# 첫번째 레이어의 파리미터 개수

In [ ]:
# 두번째 레이어의 파라미터 개수

In [ ]:
# 세번째 레이어의 파리미터 개수

### reference

- https://github.com/ukairia777/tensorflow-nlp-tutorial/blob/main/08.%20RNN/8-4.%20understanding_simplernn_and_lstm.ipynb