In [1]:
import os
import numpy as np
import matplotlib.pyplot as plt


In [2]:
import tensorflow as tf
tf.__version__


'2.10.0'

In [3]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, GRU, LSTM, Dense


# 2. Keras로 LSTM 구현하기

https://keras.io/api/layers/recurrent_layers/lstm/

사실 실제로 SimpleRNN이 사용되는 경우는 거의 없습니다. 이보다는 LSTM이나 GRU을 주로 사용하는데, 이번에는 임의의 입력에 대해서 LSTM을 사용할 경우를 보겠습니다.

In [4]:
John = [1, 0, 0, 0]
loves = [0, 1, 0, 0]
Jane = [0, 0, 1, 0]
Alex = [0, 0, 0, 1]

train_X = np.array([
    [John, loves, Jane],
    [Jane, loves, Alex]
]).astype(np.float32)

S = [0]  # subject
V = [1]  # verb
O = [2]  # object

idx2tag = ['S', 'V', 'O']

train_Y = np.array([[S, V, O], [S, V, O]]).astype(np.float32)

print("train_y", train_Y)
print("train_X의 shape", train_X.shape)
print("train_Y의 shape", train_Y.shape)


train_y [[[0.]
  [1.]
  [2.]]

 [[0.]
  [1.]
  [2.]]]
train_X의 shape (2, 3, 4)
train_Y의 shape (2, 3, 1)


In [5]:
train_X.shape


(2, 3, 4)

In [15]:
# return_state : 마지막 timestep에서의 hidden state와 cell state를 반환. return 마지막 state
# hidden state만 가지고 있으면 되니까 확인할 필요는 없으나 그냥 확인차 True로 줘봤다.
lstm = LSTM(10, return_sequences=True, return_state=True)
output = lstm(train_X)  # 전체 t의 ht,  # 마지막 시점 ht, # 마지막 시점의 Ct


In [16]:
len(output)
# output은 3개 반환,
# 첫번째꺼는 아웃풋 3개 모두 반환
# 두번째꺼는 마지막 hidden state 반환
# 세번째꺼는 마지막 cell state 반환


3

In [17]:
output[0]  # 전체 t의 ht


<tf.Tensor: shape=(2, 3, 10), dtype=float32, numpy=
array([[[-0.00899376, -0.04539685,  0.01926465, -0.04860469,
         -0.05394898,  0.06877947, -0.04457973, -0.05808468,
         -0.06371916,  0.01753202],
        [-0.03842396, -0.10881963,  0.11235847, -0.09331466,
         -0.09252215,  0.13207774, -0.07882027, -0.08910997,
         -0.11528708,  0.03173935],
        [-0.01939922, -0.05485829,  0.02886624, -0.02972645,
         -0.05264923,  0.06480226, -0.00251446,  0.01606791,
         -0.08041437,  0.1034518 ]],

       [[ 0.0176515 ,  0.01917561, -0.06987538,  0.03140642,
          0.02393693, -0.01752347,  0.05877557,  0.07560027,
          0.03528756,  0.09013127],
        [-0.01813664, -0.0661692 ,  0.02458558, -0.03371647,
         -0.02696229,  0.05673975,  0.01313801,  0.01389839,
         -0.04213139,  0.08391594],
        [ 0.03546339, -0.01931394,  0.05945326, -0.05572852,
         -0.00829104,  0.06109661,  0.01344005, -0.03978083,
          0.01262795,  0.0999321 ]

In [18]:
output[0][:, -1]  # 전체 t의 ht 에서 마지막 시점만 따로 출력


<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[-0.01939922, -0.05485829,  0.02886624, -0.02972645, -0.05264923,
         0.06480226, -0.00251446,  0.01606791, -0.08041437,  0.1034518 ],
       [ 0.03546339, -0.01931394,  0.05945326, -0.05572852, -0.00829104,
         0.06109661,  0.01344005, -0.03978083,  0.01262795,  0.0999321 ]],
      dtype=float32)>

In [19]:
output[1]  # 마지막 시점 ht


<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[-0.01939922, -0.05485829,  0.02886624, -0.02972645, -0.05264923,
         0.06480226, -0.00251446,  0.01606791, -0.08041437,  0.1034518 ],
       [ 0.03546339, -0.01931394,  0.05945326, -0.05572852, -0.00829104,
         0.06109661,  0.01344005, -0.03978083,  0.01262795,  0.0999321 ]],
      dtype=float32)>

In [20]:
output[2]  # 마지막 시점의 Ct


<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[-0.03630137, -0.11032405,  0.05311898, -0.07478952, -0.10904814,
         0.15200037, -0.00448041,  0.02939968, -0.1651406 ,  0.1808424 ],
       [ 0.07738936, -0.04519171,  0.14353076, -0.12354764, -0.01479083,
         0.11884655,  0.02332984, -0.08606914,  0.02237864,  0.23686293]],
      dtype=float32)>

In [21]:
# return_sequences = True

lstm = LSTM(3, return_sequences=True, return_state=True)
whole_seq_output, final_hidden_state, final_cell_state = lstm(train_X)

print('whole_seq_output: {}, shape: {}'.format(
    whole_seq_output, whole_seq_output.shape))
print('final_hidden_state : {}, shape: {}'.format(
    final_hidden_state, final_hidden_state.shape))
print('final_cell_state : {}, shape: {}'.format(
    final_cell_state, final_cell_state.shape))


whole_seq_output: [[[-0.07162642 -0.08404578 -0.16836044]
  [ 0.05354498 -0.08401847  0.00938375]
  [ 0.09814937 -0.05387172 -0.12563702]]

 [[ 0.06151628  0.01696187 -0.12610085]
  [ 0.15711914 -0.04452886  0.00689181]
  [ 0.26091272 -0.10581073 -0.15338148]]], shape: (2, 3, 3)
final_hidden_state : [[ 0.09814937 -0.05387172 -0.12563702]
 [ 0.26091272 -0.10581073 -0.15338148]], shape: (2, 3)
final_cell_state : [[ 0.24825564 -0.11214519 -0.29007077]
 [ 0.50272596 -0.19775653 -0.3042984 ]], shape: (2, 3)


In [22]:
from tensorflow.keras import layers, models

model = models.Sequential()  # 모델 호출
model.add(
    layers.LSTM(units=5,
                input_shape=(3, 4),
                return_sequences=True,
                name='LSTM-1'))

model.add(
    layers.Dense(
        units=3,
        activation='softmax',
        name='hidden-to-output'))  # 출력을 위한 FFN


model.compile(
    loss='sparse_categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy'])


In [23]:
model.fit(train_X, train_Y, epochs=100)


Epoch 1/100
1/1 [==============================] - 1s 1s/step - loss: 1.0756 - accuracy: 0.3333
Epoch 2/100
1/1 [==============================] - 0s 3ms/step - loss: 1.0748 - accuracy: 0.3333
Epoch 3/100
1/1 [==============================] - 0s 3ms/step - loss: 1.0739 - accuracy: 0.3333
Epoch 4/100
1/1 [==============================] - 0s 4ms/step - loss: 1.0730 - accuracy: 0.3333
Epoch 5/100
1/1 [==============================] - 0s 4ms/step - loss: 1.0722 - accuracy: 0.3333
Epoch 6/100
1/1 [==============================] - 0s 6ms/step - loss: 1.0713 - accuracy: 0.3333
Epoch 7/100
1/1 [==============================] - 0s 4ms/step - loss: 1.0705 - accuracy: 0.3333
Epoch 8/100
1/1 [==============================] - 0s 4ms/step - loss: 1.0696 - accuracy: 0.3333
Epoch 9/100
1/1 [==============================] - 0s 4ms/step - loss: 1.0687 - accuracy: 0.3333
Epoch 10/100
1/1 [==============================] - 0s 3ms/step - loss: 1.0679 - accuracy: 0.3333
Epoch 11/100
1/1 [============

In [24]:
predictions = model.predict(train_X)
for i, prediction in enumerate(predictions):
    print(prediction)
    print(np.argmax(prediction, axis=1))
    result_str = [idx2tag[c] for c in np.argmax(prediction, axis=1)]
    print("\tPrediction str: ", "".join(result_str))


1/1 [==============================] - 0s 314ms/step
[[0.40961507 0.32875708 0.26162785]
 [0.33747613 0.33031857 0.33220533]
 [0.28459403 0.33180836 0.3835976 ]]
[0 0 2]
	Prediction str:  SSO
[[0.31943414 0.3488647  0.33170113]
 [0.27150086 0.33575118 0.39274797]
 [0.18445611 0.30958122 0.50596267]]
[1 2 2]
	Prediction str:  VOO


In [25]:
model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 LSTM-1 (LSTM)               (None, 3, 5)              200       
                                                                 
 hidden-to-output (Dense)    (None, 3, 3)              18        
                                                                 
Total params: 218
Trainable params: 218
Non-trainable params: 0
_________________________________________________________________


In [26]:
for model_weight in model.weights:
    print(model_weight.name, '=>', model_weight.shape)


LSTM-1/lstm_cell_4/kernel:0 => (4, 20)
LSTM-1/lstm_cell_4/recurrent_kernel:0 => (5, 20)
LSTM-1/lstm_cell_4/bias:0 => (20,)
hidden-to-output/kernel:0 => (5, 3)
hidden-to-output/bias:0 => (3,)


### 문제1

In [ ]:
model = Sequential()
model.add(LSTM(7, input_shape=(100, 5)))
model.summary()


Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_2 (LSTM)               (None, 7)                 364       
                                                                 
Total params: 364
Trainable params: 364
Non-trainable params: 0
_________________________________________________________________


- W_forget : (num_units + input_dim + 1) * num_units
- W_input : (num_units + input_dim + 1) * num_units
- W_output : (num_units + input_dim + 1) * num_units
- W_cell : (num_units + input_dim + 1) * num_units

### 문제2

In [ ]:
model = Sequential()
model.add(LSTM(5, input_shape=(2, 10)))
model.add(Dense(1))
model.summary()


Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_3 (LSTM)               (None, 5)                 320       
                                                                 
 dense (Dense)               (None, 1)                 6         
                                                                 
Total params: 326
Trainable params: 326
Non-trainable params: 0
_________________________________________________________________


- W_forget : (num_units + input_dim + 1) * num_units
- W_input : (num_units + input_dim + 1) * num_units
- W_output : (num_units + input_dim + 1) * num_units
- W_cell : (num_units + input_dim + 1) * num_units

In [ ]:
# weight 개수 카운팅


### 문제3

In [ ]:
model = Sequential()
model.add(LSTM(5, input_shape=(2, 10), return_sequences=True))
model.add(LSTM(7))
model.add(Dense(1))
model.summary()


Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_4 (LSTM)               (None, 2, 5)              320       
                                                                 
 lstm_5 (LSTM)               (None, 7)                 364       
                                                                 
 dense_1 (Dense)             (None, 1)                 8         
                                                                 
Total params: 692
Trainable params: 692
Non-trainable params: 0
_________________________________________________________________


# 3. Keras로 GRU 구현하기

https://keras.io/api/layers/recurrent_layers/gru/

In [ ]:
train_X


array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]],

       [[0., 0., 1., 0.],
        [0., 1., 0., 0.],
        [0., 0., 0., 1.]]], dtype=float32)

In [27]:
gru = GRU(10, return_sequences=True, return_state=True)
whole_hidden_state, final_hidden_state = gru(train_X)


In [ ]:
whole_hidden_state.shape


TensorShape([2, 3, 10])

In [ ]:
final_hidden_state.shape


TensorShape([2, 10])

In [28]:
# return_sequences = True
gru = GRU(3, return_sequences=True, return_state=True)
whole_sequence_output, final_state = gru(train_X)

print('whole_seq_output: {}, shape: {}'.format(
    whole_seq_output, whole_seq_output.shape))
print('final_state : {}, shape: {}'.format(final_state, final_state.shape))


whole_seq_output: [[[-0.07162642 -0.08404578 -0.16836044]
  [ 0.05354498 -0.08401847  0.00938375]
  [ 0.09814937 -0.05387172 -0.12563702]]

 [[ 0.06151628  0.01696187 -0.12610085]
  [ 0.15711914 -0.04452886  0.00689181]
  [ 0.26091272 -0.10581073 -0.15338148]]], shape: (2, 3, 3)
final_state : [[-0.00958517  0.20244196  0.27274793]
 [-0.22368565  0.1525776   0.04306152]], shape: (2, 3)


In [29]:
from tensorflow.keras import layers, models

model = models.Sequential()  # 모델 호출
model.add(
    layers.GRU(
        units=5,
        input_shape=(3, 4),
        return_sequences=True,
        reset_after=False,
        name='GRU-1'))  # RNN 호출

# reset_after : keras 구현을 하면서 병렬처리를 위해 공식을 수정(bias를 2개로 나눔)하였는데, 원래 논문에 나온 공식으로 계산하기 위해 False로 수정
# reset gate 계산을 병렬적으로 빠르게 하고싶어서 bias를 h와 x에 각각 준다.

model.add(
    layers.Dense(
        units=3,
        activation='softmax',
        name='hidden-to-output'))  # 출력을 위한 FFN


model.compile(
    loss='sparse_categorical_crossentropy',
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.01),
    metrics=['accuracy'])


In [30]:
model.fit(train_X, train_Y, epochs=100)


Epoch 1/100
1/1 [==============================] - 1s 969ms/step - loss: 1.0845 - accuracy: 0.5000
Epoch 2/100
1/1 [==============================] - 0s 3ms/step - loss: 1.0675 - accuracy: 0.5000
Epoch 3/100
1/1 [==============================] - 0s 4ms/step - loss: 1.0515 - accuracy: 0.5000
Epoch 4/100
1/1 [==============================] - 0s 4ms/step - loss: 1.0364 - accuracy: 0.5000
Epoch 5/100
1/1 [==============================] - 0s 5ms/step - loss: 1.0219 - accuracy: 0.5000
Epoch 6/100
1/1 [==============================] - 0s 17ms/step - loss: 1.0080 - accuracy: 0.6667
Epoch 7/100
1/1 [==============================] - 0s 5ms/step - loss: 0.9944 - accuracy: 0.8333
Epoch 8/100
1/1 [==============================] - 0s 11ms/step - loss: 0.9810 - accuracy: 0.8333
Epoch 9/100
1/1 [==============================] - 0s 5ms/step - loss: 0.9677 - accuracy: 0.8333
Epoch 10/100
1/1 [==============================] - 0s 5ms/step - loss: 0.9542 - accuracy: 0.6667
Epoch 11/100
1/1 [=======

In [ ]:
predictions = model.predict(train_X)
for i, prediction in enumerate(predictions):
    print(prediction)
    print(np.argmax(prediction, axis=1))
    result_str = [idx2tag[c] for c in np.argmax(prediction, axis=1)]
    print("\tPrediction str: ", "".join(result_str))


1/1 [==============================] - 0s 438ms/step
[[9.8557788e-01 1.4102679e-02 3.1941311e-04]
 [1.6076935e-02 9.7144395e-01 1.2479113e-02]
 [5.0632996e-03 1.8666392e-02 9.7627026e-01]]
[0 1 2]
	Prediction str:  SVO
[[9.6419764e-01 3.3043835e-02 2.7585761e-03]
 [1.7866999e-02 9.6090233e-01 2.1230677e-02]
 [3.9569856e-04 2.4343718e-02 9.7526056e-01]]
[0 1 2]
	Prediction str:  SVO


In [ ]:
model.summary()


Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 GRU-1 (GRU)                 (None, 3, 5)              150       
                                                                 
 hidden-to-output (Dense)    (None, 3, 3)              18        
                                                                 
Total params: 168
Trainable params: 168
Non-trainable params: 0
_________________________________________________________________


In [ ]:
for model_weight in model.weights:
    print(model_weight.name, '=>', model_weight.shape)


GRU-1/gru_cell_4/kernel:0 => (4, 15)
GRU-1/gru_cell_4/recurrent_kernel:0 => (5, 15)
GRU-1/gru_cell_4/bias:0 => (15,)
hidden-to-output/kernel:0 => (5, 3)
hidden-to-output/bias:0 => (3,)


### 문제1

In [ ]:
model = Sequential()
model.add(GRU(9, input_dim=10, return_sequences=True, reset_after=False))
# reset_after : keras 구현을 하면서 병렬처리를 위해 공식을 수정(bias를 2개로 나눔)하였는데, 원래 논문에 나온 공식으로 계산하기 위해 False로 수정
model.add(GRU(6, reset_after=False))
model.add(Dense(3))
model.summary()


Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 gru_6 (GRU)                 (None, None, 9)           540       
                                                                 
 gru_7 (GRU)                 (None, 6)                 288       
                                                                 
 dense_6 (Dense)             (None, 3)                 21        
                                                                 
Total params: 849
Trainable params: 849
Non-trainable params: 0
_________________________________________________________________


- W_reset : (num_units + input_dim + 1) * num_units
- W_update : (num_units + input_dim + 1) * num_units
- W_new : (num_units + input_dim + 1) * num_units


In [ ]:
# 첫번째 레이어의 파리미터 개수


In [ ]:
# 두번째 레이어의 파라미터 개수


In [ ]:
# 세번째 레이어의 파리미터 개수


### reference

논문 번역 : Deepl

논문을 통해서 봐야 할 것    
모델 정리할 때 정리해야 할 것.
- 모델 architecture = hypothesis
- 모델 학습 방식 = Cost Function 오차 계산
- 성능 개선 전략 (이 논문의 독창성, 1번 2번 외의)    
이 전략들에는 카테고리가 있다. 카테고리 정리도 필요.
 - training 
 - hyper parameter
 - activation function
 - normailze

읽을때는 선질문, 후보기. 책이든 논문이든 수업이든.    
오늘 나는 궁금한게 이것이다! 를 책 표지에 썬호고 일긱 시작하면 공격적으로 읽고 들을 수 있다.

읽고 나서 중심 토픽별로 모듈화해서 가지치기해서 내가 읽었던 내용을 마인드맵으로 정리.     
논문 읽고 나서는 성능개선전략을 정리해야 한다.    
예를 들면, 
 - training 
 - hyper parameter
 - activation function
 - normailze    
이런 카테고리들을 정리해 두고 이번 논문에서는 이런 augmentation을 배웠어! 하고 적어두는것.

1독1행. 읽고 실천해라. 구현해라!

- https://github.com/ukairia777/tensorflow-nlp-tutorial/blob/main/08.%20RNN/8-4.%20understanding_simplernn_and_lstm.ipynb